### ISSUE TITLE
Not working links in the documentation

### ISSUE THREAD

**Issue by chicco785** [martel-innovate/deep-log-inspection#1]
@michelechersich All the links to configurations files are not working in the readthedocs. Not sure there is a way for "local" reference paths (e.g. syslogVM/syslog-server/config/logstash.conf) to be auto-completed with the github based url when converting to readthedocs (i doubt).

**Comment by chicco785** [comment]
Just an example. This page: [http://deep-log-inspection.readthedocs.io/en/latest/install/monasca-log-agent/ ](http://deep-log-inspection.readthedocs.io/en/latest/install/monasca-log-agent/ )
links to [http://deep-log-inspection.readthedocs.io/en/syslogVM/syslog-server/config/logstash.conf](http://deep-log-inspection.readthedocs.io/en/syslogVM/syslog-server/config/logstash.conf)

**Comment by k33rs** [comment]
Fixed by using complete Github URLs.
