### ISSUE TITLE
configuration files should not be loaded from volumes

### ISSUE THREAD

**Issue by chicco785** [martel-innovate/deep-log-inspection#19]
as already pointed out, this leads to configuration issues (what if you change configuration on one node and not on another, or the volume is not configured on a node?).
you config (or secrets) objects of docker.

**Comment by k33rs** [comment]
Note that whenever a configuration file is mounted as a volume, there is the constraint that the service run only on that particular node (node.hostname == deeplogmanager), so that the problems you mention never occur.

I will try and use config objects because one might want to run some service on many nodes and not just the manager.

**Comment by chicco785** [comment]
it may be true, but still its a "dirty" solution not aligned with the design philosophy of docker for several reasons:
* docker is an api, as such you should be able to call and configure everything from the command line of your laptop without ssh access to the remote docker swarm cluster, while config and secrets are management using `docker stack deploy`, with volumes you need to access the vm to load files.
* hostname is not documented in the installation documentation, and if the manager fails, while a new manager will be elected, services will not be launched again, leading to the service not being reachable. better solution is using a label based on node role, and assuming that a new manager will be elected. in which case using config, configuration data will be available also on the new manager.

**Comment by chicco785** [comment]
cf #22

**Comment by chicco785** [comment]
also, in case, as it should, also other services becomes replicated for scalability purposes, you would have actually faced the issue.

**Comment by k33rs** [comment]
check back [PR](https://github.com/martel-innovate/deep-log-inspection/pull/21)
