### ISSUE TITLE
Create two docker compose file versions

### ISSUE THREAD

**Issue by chicco785** [martel-innovate/deep-log-inspection#2]
Create two docker compose file versions (and explain the difference in the docs):

- docker-compoone.yml not including keystone and other services (mysql?), pre existing in FIWARE Lab.
- docker-compose-all.yml including keystone and other services, pre existing in FIWARE Lab.

**Comment by k33rs** [comment]
How about splitting the compose file in two files?

'docker-compose -f docker-compose.yml up' runs the basic services
'docker-compose -f docker-compose.yml -f docker-compose-keystone.yml up' runs all services, including keystone and mysql

**Comment by k33rs** [comment]
Done.
https://github.com/martel-innovate/deep-log-inspection/blob/master/docker-compose.yml
https://github.com/martel-innovate/deep-log-inspection/blob/master/docker-compose-keystone.yml
https://github.com/martel-innovate/deep-log-inspection/blob/master/doc/quickstart.md
https://github.com/martel-innovate/deep-log-inspection/blob/master/doc/install/install.md
