### ISSUE TITLE
replace `hostname == deeplogmanager` with a role based constraint

### ISSUE THREAD

**Issue by chicco785** [martel-innovate/deep-log-inspection#22]
using a constraint `node.role == manager` assuming we go for a solution where a single node is manager, will avoid issues related to the adoption of hostname, which:
* may not be always configurable
* limit the availability of the service when for whatever reason the node with `hostname == deeplogmanager` is not available
* ensure that the docker-compose file is less depending on host configuration.

**Comment by k33rs** [comment]
check back [PR](https://github.com/martel-innovate/deep-log-inspection/pull/21)
