### ISSUE TITLE
Redesign architecture picture

### ISSUE THREAD

**Issue by chicco785** [martel-innovate/deep-log-inspection#3]
1. The picture as a low quality (http://deep-log-inspection.readthedocs.io/en/latest/architecture/)
2. Does not show the "link" to FIWARE Lab:
    1. Show the authentication against FIWARE Lab keystone.
    2. Show the logs collection from different FIWARE Lab nodes.

**Comment by chicco785** [comment]
the picture is partially misleading, it looks like that you will have one agent for all the different FIWARE Lab Nodes, but as zurich has is agent today, all the other will have its own.

**Comment by k33rs** [comment]
modified with two FIWARE Lab Nodes, one agent each.
