### ISSUE TITLE
Log Agent: regions configuration ?

### ISSUE THREAD

**Issue by chicco785** [martel-innovate/deep-log-inspection#4]
I expect that log agent collect also the "Region" information (e.g. Zurich, Spain) to be able to filter the data by the different regions. But this is not in the configuration, nor in the documentation of the Log Agent.

**Comment by k33rs** [comment]
The region is not part of the logs, so probably it has to be hardcoded in the log agent.

**Comment by chicco785** [comment]
possible, but as earlier discussed, the log agent have to pass this information to the log api, or it will not be possible to know from which region the log is received

**Comment by k33rs** [comment]
Done.
https://github.com/martel-innovate/deep-log-inspection/blob/master/syslogVM/syslog-server/config/logstash.conf
https://github.com/martel-innovate/deep-log-inspection/blob/master/doc/install/monasca-log-agent.md
