### ISSUE TITLE
Do we really need custom version of Dockerfiles?

### ISSUE THREAD

**Issue by chicco785** [martel-innovate/deep-log-inspection#5]
We have a number of Dockerfiles:
- elasticsearch/ Dockerfile for Elasticsearch
- kibana/: Dockerfile for kibana
- logstash-transformer/: Dockerfile for logstash-transformer
- logstash-persister/: Dockerfile for logstash-persister
- monasca-log-api/: Dockerfile for Monasca Log API
- syslogVM/: Dockerfile and logstash.conf for remote syslog server

But it looks to me that:
1. Most of them are not actually used in the Docker Compose
2. Most probably, you can just build (which always better) on the official images, passing environment variables or volumes paths.

**Comment by k33rs** [comment]
True only for elasticsearch and kibana. In all other Dockerfiles some installations are done on top of official images.

N.B. syslogVM is not used in the compose file as it is just a copy of what's on Sean's VM.

**Comment by chicco785** [comment]
syslogVM/ is the agent part, right?

then we can maybe better structure the repository, by making to main directories:
log-server
log-client

the first include all the scripts or compose related to the server side, the second one, the part for the nodes that need to install for pushing data to the server

**Comment by k33rs** [comment]
restructured the repo and adjusted hyperlinks in the docs
